superhero_project/superhero_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
import superheroes

urlpatterns = [
    path('admin/', admin.site.urls),
    path('superheroes/', include('superheroes.urls')),
    path('', RedirectView.as_view(url='/superheroes/')),
]

superhero_project/superheroes/urls.py
from django.urls import path

from . import views

app_name = 'superheroes'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:hero_id>/', views.detail, name = 'detail'),
    path('new/', views.create, name = 'create'),
    path('edit/<int:hero_id>/', views.edit, name = 'edit'),
    path('delete/<int:hero_id>/', views.delete, name = 'delete')
]

superhero_project/superheroes/models.py
from django.db import models

# Create your models here.
class Superhero(models.Model):
    name = models.CharField(max_length=50)
    alter_ego = models.CharField(max_length=50)
    primary_ability = models.CharField(max_length=50)
    secondary_ability = models.CharField(max_length=50)
    catch_phrase = models.CharField(max_length=50)

    def __str__(self):
        return self.name

superhero_project/superheroes/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.urls import reverse
# from django.db.models import F
from .models import Superhero

# Create your views here.
def index(request):
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)

def detail(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    context = {
        'single_hero': single_hero
    }
    return render(request, 'superheroes/detail.html', context)

def create(request):
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        new_hero = Superhero(name=name, alter_ego=alter_ego, primary_ability=primary, secondary_ability=secondary, catch_phrase=catchphrase)
        new_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
        return render(request, 'superheroes/create.html')

def edit(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    if single_hero is None:
        return Http404
    if request.method == "POST":
        name = request.POST.get('name')
        alter_ego = request.POST.get('alter_ego')
        primary = request.POST.get('primary')
        secondary = request.POST.get('secondary')
        catchphrase = request.POST.get('catchphrase')
        single_hero.name = name
        single_hero.alter_ego = alter_ego
        single_hero.primary_ability = primary
        single_hero.secondary_ability = secondary
        single_hero.catch_phrase = catchphrase
        single_hero.save()
        return HttpResponseRedirect(reverse('superheroes:index'))
    else:
         context = {
             'hero_id': hero_id
         }
         return render(request, 'superheroes/edit.html', context)

def delete(request, hero_id):
    single_hero = Superhero.objects.get(pk=hero_id)
    if single_hero is None:
        return Http404
    single_hero.delete()
    all_heroes = Superhero.objects.all()
    context = {
        'all_heroes': all_heroes
    }
    return render(request, 'superheroes/index.html', context)
    

superhero_project/superheroes/templates/superheroes/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create New Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:create' %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="ADD!"> 
    </form>
</body>
</html>

superhero_project/superheroes/templates/superheroes/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Details</title>
</head>

<body>
    <h1>Hero</h1>
    <h2>{{single_hero.name}}</h2>

    <p>Alter Ego: {{single_hero.alter_ego}}</p>
    <p>Primary Ability: {{single_hero.primary_ability}}</p>
    <p>Secondary Ability: {{single_hero.secondary_ability}}</p>
    <p>Catch Phrase: {{single_hero.catch_phrase}}</p>
</body>

</html>

superhero_project/superheroes/templates/superheroes/edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit Hero</title>
</head>
<body>
    <form action="{% url 'superheroes:edit' hero_id %}" method="post">
        {% csrf_token %}
        Name: <input type="text" name="name" id="name"><br />
        Alter Ego: <input type="text" name="alter_ego" id="alter_ego"><br />
        Primary Ability: <input type="text" name="primary" id="primary"><br />
        Secondary Ability: <input type="text" name="secondary" id="secondary"><br />
        Catchphrase: <input type="text" name="catchphrase" id="catchphrase"><br />
        <input type="submit" value="EDIT!"> 
    </form>
    
</body>
</html>

superhero_project/superheroes/templates/superheroes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Superhero Index</title>
</head>
<body>
    <h1>List of Heroes</h1>
    <ul>
        {% for hero in all_heroes%}
        <li> <h2> {{hero.name}} - <a href="{% url 'superheroes:detail' hero.id %}">Click for Details</a> </h2> </li>
        <a href="{% url 'superheroes:edit' hero.id %}">Edit</a>
        <a href="{% url 'superheroes:delete' hero.id %}">Delete</a>
        {% endfor %}
    </ul>   
    <a href="{% url 'superheroes:create' %}">Add New Hero</a>
</body>
</html>